<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_next_green</name>
   <tag></tag>
   <elementGuidId>9e3deb73-843c-4f60-bf4b-2673cab95e8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//android.widget.ImageView[@clickable='true'])[last()]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//android.widget.ImageView[@clickable='true'])[last()]</value>
      <webElementGuid>a89e8116-de95-4e47-9609-39695b581bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
