<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detalle_pantalla_contenedor</name>
   <tag></tag>
   <elementGuidId>2cf71b7b-84d9-4944-af0d-4476af19023b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//android.widget.ScrollView</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//android.widget.ScrollView</value>
      <webElementGuid>3cc11ccc-dd03-43ed-86d9-59cc09a60da1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
